stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind
  
  variables: 
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t ninomunich/ci-cd:1.0 app/.
    - docker push ninomunich/ci-cd:1.0

deploy_gcp:

  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH_KEY
  
  script:
      - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf ./ci-cd/ && sudo git clone https://gitlab.com/ninomunich/ci-cd.git && cd ci-cd && sudo chmod +x ./script.sh && ./script.sh"
